language: objective-c
osx_image: xcode7.1

env:
  - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES

xcode_workspace: Overcoat.xcworkspace
xcode_scheme:
  - OvercoatApp-iOS
  - OvercoatApp-OSX
xcode_sdk:
  - iphonesimulator
  - macosx

matrix:
  exclude:
    - xcode_scheme: OvercoatApp-iOS
      xcode_sdk: macosx
    - xcode_scheme: OvercoatApp-OSX
      xcode_sdk: iphonesimulator
